/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParksParkIdRouteImport } from './routes/parks.$parkId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParksParkIdRoute = ParksParkIdRouteImport.update({
  id: '/parks/$parkId',
  path: '/parks/$parkId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parks/$parkId': typeof ParksParkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parks/$parkId': typeof ParksParkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parks/$parkId': typeof ParksParkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/parks/$parkId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/parks/$parkId'
  id: '__root__' | '/' | '/parks/$parkId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParksParkIdRoute: typeof ParksParkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parks/$parkId': {
      id: '/parks/$parkId'
      path: '/parks/$parkId'
      fullPath: '/parks/$parkId'
      preLoaderRoute: typeof ParksParkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParksParkIdRoute: ParksParkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
